apiVersion: apps/v1
kind: Deployment
metadata:
  name: npc-maker
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: npc-maker
  template:
    metadata:
      labels:
        app: npc-maker
    spec:
      containers:
      - image: <+artifacts.primary.image>
        name: npc-maker
        ports:
        - containerPort: 3000
      imagePullSecrets:
          - name: docker-registry-secret1