apiVersion: apps/v1
kind: Deployment
metadata:
  name: npc-maker-deployment
  labels:
    app: npc-maker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: npc-maker
  template:
    metadata:
      labels:
        app: npc-maker
    spec:
      containers:
        - name: npc-maker-container
          image: antomi12332/npc-maker:latest
          ports:
            - containerPort: 3000
          env:
            - name: dev
              valueFrom:
                secretKeyRef:
                  name: npc-maker-secrets
                  key: dev
            - name: NEXT_PUBLIC_SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: npc-maker-secrets
                  key: NEXT_PUBLIC_SUPABASE_URL
            - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: npc-maker-secrets
                  key: NEXT_PUBLIC_SUPABASE_ANON_KEY
            - name: NEXT_PUBLIC_SUPABASE_GRAPHQL_URL
              valueFrom:
                secretKeyRef:
                  name: npc-maker-secrets
                  key: NEXT_PUBLIC_SUPABASE_GRAPHQL_URL