apiVersion: apps/v1
kind: Deployment
metadata:
  name: npc-maker
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: npc-maker
  template:
    metadata:
      labels:
        app: npc-maker